### ISSUE TITLE
Training a model with the BOOKSUM dataset might lead to data leakage？

### ISSUE THREAD

**Issue by CxsGhost** [zexuanqiu/CLongEval#1]
Hello, in this work I see that the novel summaries are from the BookSum dataset. May I ask if they were selected from the entire BookSum dataset? 
The BookSum dataset has about 10,000 entries at the chapter level. How many entries does the Clongeval assessment set cover? 
There might be data leakage when using BookSum to train LLMs. Could you provide more detailed information about the construction of this task? Thank you!

**Comment by zexuanqiu** [comment]
Hi there! Thank you for your interest in our work. We acknowledge that the original dataset may have been utilized during the training phase of LLMs. To address potential data leakage issues, we have taken steps to mitigate them. First, we translate the BookSum dataset into Chinese. For the input text, we select continuous paragraphs or chapters of expected length and concatenate them to create long-context inputs.  This makes the input significantly different from the original BookSum dataset.  Second, we employ GPT-4-Turbo to aggregate the corresponding summaries of these selected paragraphs or chapters into a comprehensive summary.   Through our observations, the generated global summary differs in content and style from the original local summaries, resulting in a more abstract reference summary. These efforts are made to minimize any potential data leakage issues.

Additionally, we only utilize a subset of the dataset, extracting continuous paragraphs until the quantity requirements of the dataset are met.

**Comment by CxsGhost** [comment]
Thank you for your answer and for this excellent work
