### ISSUE TITLE
yi-200k的评测结果

### ISSUE THREAD

**Issue by nuoma** [zexuanqiu/CLongEval#2]
你好，零一万物的API刚刚上线，提供yi-34b-chat-200k（https://platform.lingyiwanwu.com/）。和OpenAI API格式兼容，不知道是否可以跑一下Eval。希望与您取得联系，我的wx：17317907343 -马诺

**Comment by zexuanqiu** [comment]
Hi 马诺你好。可以按照repo给出的代码稍微改一下就能跑你们自己的api，这个改起来应该很快的。

**Comment by datalee** [comment]
期待你的结果
