### ISSUE TITLE
vllm不支持的模型，怎么进行测试？

### ISSUE THREAD

**Issue by Pride-Huang** [zexuanqiu/CLongEval#5]
我目前在测试一个teleChat模型，发现CLong需要使用vllm库，但是该库函数目前还不支持一些大模型。在这样的情况下，应该怎么处理？

**Comment by zexuanqiu** [comment]
你好，可以在inference.py 新增一个推理函数，使用transformer库的原生推理方法就行，但这样可能比较慢。
